services:
  web:
    build: .
    ports:
      - "8000:4567"
  node:
    image: "node:16"
  mongo:
    container_name: mongo
    image: mongo:6.0.3
    restart: always
    ports:
      - "27018:27108"
    volumes:
      - /opt/mongodb/data:/data/db