services:
  web:
    build: .
    ports:
      - "8000:4567"
  node:
    image: "node:16"
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './dockervolume/mongodb:/data/db'
    links:
      - "database:burritoshopdb"
    environment:
      - DATABASE_URL="mongodb://burritoshopdb:27017"